name: Feature Request
description: 機能追加要望
title: '[Feature]: '
labels: ["Type: Feature"]
body:
  - type: input
    id: function
    attributes:
      label: 機能名
      description: 機能追加を行う機能名を入力してください。
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        機能追加の概要を入力してください。
        資料等がある場合は併せて添付してください。
    validations:
      required: true
  - type: textarea
    id: remakrs
    attributes:
      label: 備考
      description: 追記事項があれば入力してください。
