name: Feature Request
description: 機能追加/仕様変更
title: '[Feature]: '
labels: ["feature"]
body:
  - type: input
    id: function
    attributes:
      label: 機能名
      description: 機能追加/仕様変更を行う機能名を入力してください。
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        機能追加/仕様変更を行う機能名を入力してください。
        資料等がある場合は併せて添付してください。
    validations:
      required: true
  - type: textarea
    id: remakrs
    attributes:
      label: 備考
      description: 機能追加/仕様変更に伴う留意事項等、追記事項があれば入力してください。
